language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'

cache: pip

install:
  - pip install .
  - pip install flake8 pytest
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install black; fi

script:
  - flake8 ./kieli.py ./test_kieli.py
  - pytest -vv
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then black --check .; fi

notifications:
  irc:
    channels:
      - 'chat.freenode.net#8Banana'
    skip_join: true
    on_success: change
    on_failure: always
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}'
