language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
  - 'nightly'

cache: pip

install:
  - pip install .
  - pip install pylint black pytest

script:
  - pylint .
  - black --check
  - pytest -vv

matrix:
  allow_failures:
    - python: 'nightly'
