# Python >=3.7 is only available on `sudo: enabled`.
sudo: enabled

language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
  - 'nightly'

cache: pip

install:
  - pip install .
  - pip install pylint black pytest

script:
  - pylint .
  - black --check
  - pytest -vv

notifications:
  irc:
    channels:
      - 'chat.freenode.net#8Banana'
    skip_join: true
    on_success: change
    on_failure: always
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}'

matrix:
  allow_failures:
    - python: 'nightly'
